### ISSUE TITLE
internal server error  when user is logged in and try to click "Lets Go"

### ISSUE THREAD

**Issue by riyazsarah** [tusharvickey1999/FastAPI-MongoDB#4]
internal server error  when user is logged in and try to click "Lets Go"

**Comment by tusharsnx** [comment]
Thanks for submitting the issue!
I can see the same warning message. I think I know what the issue is, and will try to push a fix ASAP.

**Comment by tusharsnx** [comment]
Can you try logging in again? It should be fixed now.
